alloy:
  alloy:
    stabilityLevel: "experimental"
    controller:
      type: 'deployment'
    configMap:
      create: true
      content: |
        logging {
          level = "debug"
        }

        // INGESTION
        otelcol.receiver.otlp "default" {
          grpc { }

          output {
            traces  = [otelcol.exporter.otlp.tempo.input]
          }
        }

        // EXPORTERS
        otelcol.exporter.debug "default" {
          verbosity = "detailed"
        }

        otelcol.exporter.otlp "tempo" {
          client {
            endpoint = "tempo:4317"

            tls {
              insecure = true
            }
          }
        }
