alloy:
  alloy:
    stabilityLevel: "experimental"
    controller:
      type: 'deployment'
    extraPorts:
      - name: "grpc"
        port: 4317
        targetPort: 4317
      - name: "http"
        port: 4318
        targetPort: 4318
    configMap:
      create: true
      content: |
        logging {
          level = "debug"
        }

        // INGESTION
        otelcol.receiver.otlp "default" {
          grpc { }

          output {
            metrics = [otelcol.exporter.prometheus.default.input]
            traces  = [otelcol.exporter.otlp.tempo.input, otelcol.connector.servicegraph.default.input]
          }
        }

        // PROCESSORS
        otelcol.receiver.prometheus "default" {
          output {
            metrics = [otelcol.exporter.debug.default.input, prometheus.remote_write.default.receiver]
          }
        }

        otelcol.connector.servicegraph "default" {
          dimensions = ["http.method", "http.target"]
          output {
            metrics = [otelcol.exporter.otlp.tempo.input]
          }
        }

        // EXPORTERS
        otelcol.exporter.debug "default" {
          verbosity = "detailed"
        }

        prometheus.remote_write "default" {
          endpoint {
            url = "http://prometheus-server.argocd-apps.svc/api/v1/write"
            remote_timeout = "240s"
          }
        }

        otelcol.exporter.otlp "tempo" {
          client {
            endpoint = "http://tempo.argocd-apps.svc:4317"

            tls {
              insecure = true
            }
          }
        }
