grafana:
  # -- Deploy Grafana if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration) for full values reference.
  enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          uid: loki
          type: loki
          url: http://{{ .Release.Name }}-loki-gateway
          isDefault: false
        - name: Mimir
          uid: prom
          type: prometheus
          url: http://{{ .Release.Name }}-mimir-nginx/prometheus
          isDefault: true
        - name: Tempo
          uid: tempo
          type: tempo
          url: http://{{ .Release.Name }}-tempo-query-frontend:3100
          isDefault: false
          jsonData:
            tracesToLogsV2:
              datasourceUid: loki
            lokiSearch:
              datasourceUid: loki
            tracesToMetrics:
              datasourceUid: prom
            serviceMap:
              datasourceUid: prom
loki:
  # -- Deploy Loki if enabled. See [upstream readme](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#values) for full values reference.
  enabled: true
mimir:
  # -- Deploy Mimir if enabled. See [upstream values.yaml](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml) for full values reference.
  enabled: true
tempo:
  # -- Deploy Tempo if enabled.  See [upstream readme](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/README.md#values) for full values reference.
  enabled: true

# prometheus:
#   server:
#     extraFlags:
#       - web.enable-remote-write-receiver
#     extraArgs:
#       enable-feature: exemplar-storage
#   kube-state-metrics:
#     enabled: false
#   prometheus-node-exporter:
#     enabled: false
#   alertmanager:
#     enabled: false
#   prometheus-pushgateway:
#     enabled: false
#   extraScrapeConfigs: |
#     - job_name: 'argocd-server'
#       metrics_path: /metrics
#       static_configs:
#         - targets:
#           - argocd-server-metrics.argocd.svc.cluster.local:8083
#     - job_name: 'argocd-repo-server'
#       metrics_path: /metrics
#       static_configs:
#         - targets:
#           - argocd-repo-server-metrics.argocd.svc.cluster.local:8084
#     - job_name: 'argocd-application-controller'
#       metrics_path: /metrics
#       static_configs:
#         - targets:
#           - argocd-application-controller-metrics.argocd.svc.cluster.local:8082