apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm-deployment
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
      - name: otel-lgtm
        image: grafana/otel-lgtm
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm-svc
spec:
  selector:
    app: lgtm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
