configs:
  params:
    otlp.address: 'alloy.argocd-apps.svc.cluster.local:4317'
  cm:
    timeout.reconciliation: 60s
controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
commitServer:
  metrics:
    enabled: true
notifications:
  metrics:
    enabled: true