configs:
  params:
    otlp.address: 'alloy.argocd-apps.svc:4317'
  cm:
    timeout.reconciliation: 60s
  secret:
    argocdServerAdminPassword: '$2a$10$JoLQ18GPi/HRWjoibw1PierKicQ8TWIWzMDp9mIXrI/YyZnQjoVOS'
controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
redis:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
commitServer:
  metrics:
    enabled: true
notifications:
  metrics:
    enabled: true