grafana:
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: loki
          uid: loki
          type: loki
          url: http://loki.argocd-apps.svc:3100
          isDefault: false
        - name: prometheus
          uid: prom
          type: prometheus
          url: http://prometheus-server.argocd-apps.svc
          isDefault: true
          jsonData:
            nodeGraph:
              enabled: true
        - name: tempo
          uid: tempo
          type: tempo
          url: http://tempo.argocd-apps.svc:3100
          isDefault: false
          jsonData:
            nodeGraph:
              enabled: true
            tracesToMetrics:
              datasourceUid: prom
            tracesToLogs:
              datasourceUid: 'loki'
            serviceMap:
              datasourceUid: prom