grafana:
  adminpassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: prom
          type: prometheus
          url: http://prometheus-server.argocd-apps.svc
          isDefault: true
        - name: Tempo
          uid: tempo
          type: tempo
          url: http://{{ .Release.Name }}-tempo-query-frontend:3100
          isDefault: false
          jsonData:
            tracesToMetrics:
              datasourceUid: prom
            serviceMap:
              datasourceUid: prom