grafana:
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          uid: prom
          type: prometheus
          url: http://prometheus-server.argocd-apps.svc
          isDefault: true
        - name: tempo
          uid: tempo
          type: tempo
          url: http://tempo.argocd-apps.svc:3100
          isDefault: false
          jsonData:
            tracesToMetrics:
              datasourceUid: prom
            serviceMap:
              datasourceUid: prom